services:
  salespath-api:
    image: salespath-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO=
      - MYSQL_URL=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - JOPENCAGE_API_KEY=