name: Deploiement sur EC2

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: "DEV"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Vérifier que le code source correspond à la branche spécifiée
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    # 2. Installer Maven et Java
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. Nettoyer et construire le projet Maven
    - name: Build with Maven
      run: |
        cd SalesPathAPI
        mvn clean package -DskipTests

    # 4. Vérifier que le fichier .jar est bien généré
    - name: Check generated artifact
      run: |
        ls -l SalesPathAPI/target

    # 5. Se connecter à AWS pour pouvoir push l'image Docker
    - name: Login to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-west-3

    # 6. Construire et pousser l'image Docker
    - name: Build and push Docker image
      run: |
        cd SalesPathAPI
        docker build -t api-salespath:latest .
        docker tag api-salespath:latest 345594604531.dkr.ecr.eu-west-3.amazonaws.com/api-salespath:latest
        docker push 345594604531.dkr.ecr.eu-west-3.amazonaws.com/api-salespath:latest

    # 7. Déployer l'application sur l'instance EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull 345594604531.dkr.ecr.eu-west-3.amazonaws.com/api-salespath:latest
          docker stop container_api || true
          docker rm container_api || true
          docker run -d -p 8080:8080 --name container_api 345594604531.dkr.ecr.eu-west-3.amazonaws.com/api-salespath:latest
      env:
        AWS_REGION: eu-west-3
